"""add app_error_logs table

Revision ID: 7f195bdf2f2f
Revises: 8b9f7fe09238
Create Date: 2026-05-10 15:37:19.869420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f195bdf2f2f'
down_revision = '8b9f7fe09238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_error_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_error_logs_status_code'), ['status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_error_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_app_error_logs_created_at'))

    op.drop_table('app_error_logs')
    # ### end Alembic commands ###
